conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: pam
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: periodic
    mask_ratio: !!python/tuple [5,1]
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.5, 0.7]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
