conditioning:
  method: ps+tvreg
  params:
    scale: 1.0

data:
  name: pam
  root: ./data/samples4/
  
simple_sr:
    model_path: 'simple_sr/models/model_ckpt_steps_5000.ckpt'

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    mask_ratio: !!python/tuple [5,1] # for periodic
    mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.8, 0.8]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0
