data:
  name: pam
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: periodic
    mask_ratio: (5,1)
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256
