conditioning:
  method: ps+reg
  params:
    scale: 1.0

data:
  name: pam
  root: ./data/natural/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.0
